server:
  port: 8083
spring:
  datasource:
    master:
      username: root
      password : root
      url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8
      driverClassName: com.mysql.cj.jdbc.Driver

